repos:
  # Hook para verificar segredos com gitleaks
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.1
    hooks:
      - id: gitleaks

  # Hook para verificar tipos do TypeScript
  - repo: local
    hooks:
      - id: typescript-check
        name: TypeScript Check
        entry: bash -c 'npm run type-check'
        language: system
        types: [file]
        files: \.(ts|tsx)$
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

  # Hook para lint
  - repo: local
    hooks:
      - id: eslint
        name: ESLint
        entry: bash -c 'npm run lint'
        language: system
        types: [file]
        files: \.(ts|tsx|js|jsx)$
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

